accounts/urls.py
from django.urls import path
from .views import *
urlpatterns = [
	path('login/',LoginChatView.as_view(),name='login'),
	path('register',RegisterChatView,name='register'),
	path('logout',LogoutChatView.as_view(),name='logout'),
	path('edit_profile',UpdateAccountView,name='edit_profile'),
	path('profile/<int:id>',AccountView,name='profile'),
]

chat/urls.py
from django.urls import path
from .views import *
urlpatterns = [
	path('',HomeView,name='home'),
	path('create_chat/',CreateChatView,name='create_chat'),
	path('chat/<int:id>',ChatView,name='chat'),
	path('chat/<int:pk>/message/delete/<int:id>',DeleteChatView,name='delete'),
	path('chat/<int:pk>/message/edit/<int:id>',EditChatView,name='edit'),
	]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chat.urls')),
    path('accounts/',include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
	user= models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
	bio = models.CharField(max_length=100,null=True,blank=True)
	image= models.ImageField(upload_to='images/profile',null=True,blank=True)

	def __str__(self):
		return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from datetime import datetime
# Create your models here.

class RoomChat(models.Model):
	room_name = models.CharField(max_length=100,unique=True)
	secret_key = models.CharField(max_length=16,null=True,blank=True)
	user = models.ManyToManyField(User,related_name='users')
	room_url = models.SlugField(max_length=100,null=True,blank=True)

	def save(self,*args,**kwargs):
		self.room_url=slugify(self.room_name) 
		super(RoomChat,self).save(*args,**kwargs)

	def __str__(self):
		return self.room_name

class Message(models.Model):
	user= models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
	body = models.TextField()
	chat_channel = models.ForeignKey(RoomChat,on_delete=models.CASCADE)
	date= models.DateTimeField(default=datetime.now)

	def __str__(self):
		return str(self.user)

accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UserChangeForm
from django.contrib.auth.models import User
class LoginForm(AuthenticationForm):

	class Meta:
		model = User
		fields = '__all__'

class RegisterForm(UserCreationForm):

	class Meta:
		model = User
		fields = ['username','password1','password2']
class UpdateAccountForm(UserChangeForm):

	class Meta:
		model = User
		fields = ['username']
class UpdateProfileForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ['bio','image']

chat/forms.py
from django import forms
from .models import *
class RoomCreateForm(forms.ModelForm):

	class Meta:
		model = RoomChat
		fields = ['room_name']
		widgets= {
		'room_name':forms.TextInput(attrs={'class':'form-control'}),
		}

class MessageForm(forms.ModelForm):
	body = forms.CharField(label='',widget=forms.TextInput(attrs={'class':'form-control'}))
	class Meta:
		model= Message
		fields = ['body']

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth.views import LoginView,LogoutView
# Create your views here.
from django.contrib.auth.models import User
from django.views.generic import UpdateView
from django.contrib.auth import login,authenticate
from django.contrib.auth.decorators import login_required
from .forms import *
class LoginChatView(LoginView):
	model= User
	template_name= 'pages/login.html'
	form_class = LoginForm

def RegisterChatView(request):

	if request.method == "POST":
		form= RegisterForm(request.POST)
		if form.is_valid():
			form.save()
			username=request.POST.get('username')
			password=request.POST.get('password1')
			user = authenticate(username=username,password=password)
			if user is not None:
				login(request,user)
				return redirect(reverse('home'))
	else:
		form= RegisterForm()
	context= {
	'form':form
	}
	return render(request,'pages/register.html',context)

class LogoutChatView(LogoutView):
	model =User
	template_name= 'pages/logout.html'
login_required
@login_required
def UpdateAccountView(request):
	profile = Profile.objects.get(user=request.user.id)
	if request.method == "POST":
		form1= UpdateAccountForm(request.POST,instance=request.user)
		form2 = UpdateProfileForm(request.POST,request.FILES,instance=profile)
		if form1.is_valid() and form2.is_valid():
			form1.save()
			form2.save()
			return redirect(reverse('profile',args=[request.user.id]))
	else:
		form1 = UpdateAccountForm(instance=request.user)
		form2 = UpdateProfileForm(instance=profile)
	context = {
	'form1':form1,
	'form2':form2
	}
	return render(request,'pages/edit_profile.html',context)

def AccountView(request,id):
	profile = Profile.objects.get(user=id)
	context = {
	'profile':profile
	}
	return render(request,'pages/profile.html',context)

chat/views.py
from django.shortcuts import render,redirect
from django.urls import reverse,reverse_lazy
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .test import *
from django.contrib import messages
from .encrypt import encryption_text,dencryption_text
# Create your views here.
@login_required
def HomeView(request):
	username= request.user
	if request.method =="POST":
		room_name=request.POST.get('room_name')
		secret_key=request.POST.get('secret_key')

		if RoomChat.objects.filter(room_name=room_name,secret_key=secret_key).exists():
			roomchat=RoomChat.objects.get(room_name=room_name)
			roomchat.user.add(User.objects.get(id=request.user.id))
			return redirect(reverse('chat',args=[roomchat.id]))
		else:
			messages.info(request,'Incorrect Chat Name or Secret Key.')
	context = {
		
	}
	return render(request,'pages/home.html',context)
@login_required
def ChatView(request,id):
	chat =RoomChat.objects.get(id=id)
	messages =  Message.objects.filter(chat_channel=chat)
	if request.method == "POST":
		form= MessageForm(request.POST)
		if form.is_valid():
			myform =form.save(commit=False)
			myform.user= request.user
			myform.body =encryption_text(myform.body)
			myform.chat_channel=chat
			myform.save()
			return redirect(reverse('chat',args=[chat.id]))

	else:
		form=MessageForm()
	if 'leave' in request.GET:
		chat.user.remove(request.user)
		return redirect(reverse('home'))
	context={
	'chat':chat,
	'form':form,
	'chat_messages':messages
	}

	return render(request,'chat.html',context)

def DeleteChatView(request,pk,id):
	message= Message.objects.get(id=id)
	if request.user.id == message.user.id:
		if request.method == "POST":
			message.delete()
	return HttpResponseRedirect(reverse('chat',args=[pk]))

def EditChatView(request,pk,id):
	message= Message.objects.get(id=id)
	en= dencryption_text(message.body)
	if request.method == 'POST':
		message.body=encryption_text(request.POST.get('body'))
		message.save()
		return redirect(reverse('chat',args=[pk]))
	context = {
	'en':en,
	'message':message,
	}
	return render(request,'pages/edit_message.html',context)


def CreateChatView(request):
	if request.method =='POST':
		form= RoomCreateForm(request.POST)
		if form.is_valid():
			myform =form.save(commit=False)
			myform.secret_key=secret_key_generate()
			myform.save()
			myform.user.add(User.objects.get(id=request.user.id))
			return redirect(reverse('chat',args=[myform.pk]))
	else:
		form = RoomCreateForm()

	context={
		'form':form,
	}
	return render(request,'pages/create_chat.html',context)

chat/templates/chat.html
{% extends 'base.html' %}
{% block title %}
    {{chat}} Room 
{% endblock title %}
{% block content %}
{% load lower_filter %}
<br>
{% if chat.id|checking:user.id %}

<div class=" alert alert-secondary">
    <h1 class="text-center" >{{chat}} 

  
  
      </h1>
<form method="get" dir="rtl">
  <button type="submit" style="border: none;
    background: none;" name="leave" >Leave</button>
  <p>secret_key : {{chat.secret_key}}</p> </form>
    </div>
<div class="alert alert-secondary" style="min-height:75px;">
{% for message in chat_messages %}
<div class="alert alert-dark" >
<p><strong><a href="{% url 'profile' message.user.id %}" style="color:black;">{{message.user}}</a></strong></p>
<p>{{message.body|dencryption_text}}</p>
<p>{{message.date}}</p>
{% if user.id == message.user.id %}
    

<form method="POST" dir="rtl" action="{% url 'delete' chat.id message.id %}" >
  {% csrf_token %}  
  <button style="border:none; background:none;" type="submit" name="delete" >delete</button>
  <button style="border:none; background:none;" type="submit"><a style="text-decoration:none; color:black;" href="{% url 'edit' chat.id message.id %}">Edit</a></button>
</form>
{% endif %}

</div>
  
{% endfor %}
</div>
<form class="alert alert-secondary" method='post' >
  {% csrf_token %}  
  {{form.as_p}}
        <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit" >Send</button>
    </div>
</form>
{% else %}
<h1 class=" alert alert-secondary">
  sorry !You are not allowed to this page !
</h1>

{% endif %}


{% endblock content %}

templates/base.html
<!doctype html>
  {% load static %}
<html lang="ar" dir="ltr">
  <head>
    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/icon.ico' %}"/>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.rtl.min.css" integrity="sha384-dc2NSrAXbAkjrdm9IYrX10fQq9SDG6Vjz7nQVKdKcJl3pC+k37e7qJR5MVSCS+wR" crossorigin="anonymous">
    <title>
{% block title %}
    My Chat App
{% endblock title %}
</title>
  </head>
  <body>
<nav class= "navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mo-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
            
           <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'create_chat' %}">New Chat</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Account
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'edit_profile' %}">Settings</a></li>
            <li><a class="dropdown-item" href="{% url 'profile' user.id %}">Show Profile</a></li>
          </ul>
        </li>
    {% else %}
                  <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
        </li> 
        {% endif %}
    
      </ul>
      {% if user.is_authenticated %}
          
      
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="">{{user}}</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

    <div class="container" >
{% block content %}

{% endblock %}
</div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/pages/create_chat.html
{% extends 'base.html' %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Django Chat</h1>
    
    <form class=' alert alert-secondary' method="post" >
      {% csrf_token %}  
      {{form.as_p}}
      <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit" >Create</button>
    </div>
    </form>
{% endblock content %}

templates/pages/edit_message.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}

<br>
{% if message.user.id == user.id %}
    

    <h1 class="text-center alert alert-secondary" >Edit Message</h1>
<div class="alert alert-secondary" style="min-height:75px;">

<form class="alert alert-secondary" method='post' >
  {% csrf_token %}

  <input type="text" name="body" value="{{en}}" class="form-control" title="" required="" id="id_body">        <div class="d-grid gap-2">

      <button class="btn btn-dark mt-2" type="submit" >edit</button>
    </div>

</form>
{% else %}
    <h1 class="text-center alert alert-secondary" >You do not have permission to access the page</h1>
{% endif %}
{% endblock content %}

templates/pages/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}
    settings
{% endblock title %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Edit Profile</h1>
<div class="alert alert-secondary" style="min-height:75px;">

<form class="alert alert-secondary" method='post' enctype= "multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form1 %}
  {% bootstrap_form form2 %}
  {% buttons %}
        <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit" >Save</button>
    </div>
  {% endbuttons %}
</form>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Django Chat</h1>
    
    <form class=" alert alert-secondary" method="post">
{% csrf_token %}
      <p><label for="id_room_name">Room name:</label> <input type="text" name="room_name" class="form-control" maxlength="100"  id="id_room_name"></p>
<p><label for="id_secret_key">Secret key:</label> <input type="password" name="secret_key" required class="form-control" maxlength="16" id="id_secret_key"></p>
      <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit">join</button>
    </div>
    {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message}}</li>
    {% endfor %}
  </ul>
{% endif %}
    </form>
{% endblock content %}

templates/pages/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}
  login
{% endblock title %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Login</h1>
<div class="alert alert-secondary" style="min-height:75px;">

<form class="alert alert-secondary" method='post' >
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
        <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit" >Login</button>
    </div>
  {% endbuttons %}
</form>
/*message with html*/
{% comment %}message with html{% endcomment %}

{% endblock content %}

templates/pages/logout.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}
    Logged Out
{% endblock title %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Logged Out</h1>
<div class="alert alert-secondary" style="min-height:75px;">
  <p>Thanks for spending some quality time with the web site today.
</p>
<p><a href="{% url 'login' %}">Login Again</a></p>
</div>
{% endblock content %}

templates/pages/profile.html
{% extends 'base.html' %}{% load static %}{% load bootstrap5 %}
{% block title %} {{profile.user}} Profile{% endblock title %}

{% block content %} <br> <h1
class="text-center alert alert-secondary" >{{profile.user}}'s Profile</h1> <div
class="alert alert-secondary" style="min-height:75px;">

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      {% if profile.image %}
      <img src="{{profile.image.url}}" class="img-fluid rounded-start" alt="...">

{% else %}
      <img src="{% static 'images/default_profile_pic.jpg' %}" class="img-fluid rounded-start" alt="...">
                        
      
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{profile.user}}</h5>
        {% if profile.bio %}
        <p class="card-text">{{profile.bio}}</p>
    
{% else %}
        <p class="card-text">bio</p>
                    
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/pages/register.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block title %}
  register
{% endblock title %}
{% block content %}
<br>
    <h1 class="text-center alert alert-secondary" >Register</h1>
<div class="alert alert-secondary" style="min-height:75px;">

<form class="alert alert-secondary" method='post' >
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
        <div class="d-grid gap-2">

      <button class="btn btn-dark" type="submit" >Register</button>
    </div>
  {% endbuttons %}
</form>
{% endblock content %}